bionic_university_project:
    resource: "@BionicUniversityProjectBundle/Controller/"
    type:     annotation
    prefix:   /proj

#bionic_university_blog:
#    resource: "@BionicUniversityBlogBundle/Controller/"
#    type:     annotation
#    prefix:   /

